"""empty message

Revision ID: c26d033800ed
Revises: f3d8bffea6dd
Create Date: 2018-08-28 01:15:46.739000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c26d033800ed'
down_revision = 'f3d8bffea6dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('genre_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'book', 'genre', ['genre_id'], ['genre_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'book', type_='foreignkey')
    op.drop_column('book', 'genre_id')
    # ### end Alembic commands ###
