"""empty message

Revision ID: d41666fee7b9
Revises: a714de62d8c1
Create Date: 2018-08-27 14:53:21.925000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd41666fee7b9'
down_revision = 'a714de62d8c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('status', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book', 'status')
    # ### end Alembic commands ###
