"""empty message

Revision ID: fb9df644b8d9
Revises: 0c113dab43ce
Create Date: 2018-08-27 23:51:25.838000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb9df644b8d9'
down_revision = '0c113dab43ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book', 'image')
    # ### end Alembic commands ###
